### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by MikhailPorechenkov68** [CheckbookWeb/api#2]
Here are my codes.

    SECRET = ’Secret Key from Checkbook Account'
    msg = 'POSTapplication/json/api/v2/check/digital'
    signature = base64.b64encode(hmac.new(SECRET, msg=msg, digestmod=hashlib.sha256).digest()).decode()

    params= { "first_name" : "first",
              "last_name" : "last",
              "recipient" : “a@b.com|Publishable Key from Checkbook Account",
              "amount" : 300 }

    url = 'http://www.checkbook.io/api/v2/check/digital'
    data = urllib.urlencode(params)
    request = urllib2.Request(url, data)
    base64string = base64.encodestring('%s:%s' % (SECRET, signature)).replace('\n', '')
    request.add_header("Authorization", "Basic %s" % base64string)
    response = urllib2.urlopen(request)
    result = response.read()

    return result

I am getting 500 error on this api call.

**Comment by aleer3za** [comment]
Looks like the authentication is incorrect. Please check out the checkbook v2 [api documentation](https://github.com/CheckbookWeb/api/blob/master/DirectAPI.md) to see how to generate the auth keys: 

```
import datetime
from urlparse import urlparse
import json
publishable_key = "CHECKBOOK PUBLISHABLE KEY"
signing_key = "CHECKBOOK SECRET KEY"
date = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')
msg = 'POST' + 'application/json' + date + urlparse(''/v2/check/digital).path 
dig = hmac.new(str(signing_key),msg=str(msg),
                 digestmod=hashlib.sha256).digest()
sig = base64.b64encode(dig).decode()

headers = {'Authorization': '%s:%s' % (publishable_key, sig),
                'Date': date}

data= { "first_name" : "first",
          "last_name" : "last",
          "recipient" : “email@gmail.com",
          "amount" : 1.00 }

r = requests.post(“https://sandbox.checkbook.io/api/v2/check/digital”,data=json.dumps(data),headers=headers)
```
